from app.db.database import AsyncSessionLocal
from app.models.tool import Tool
from sqlalchemy import select

DEFAULT_TOOLS = [
    # ── RECON ─────────────────────────────────────────────────────────────────
    {
        "name": "Nmap - Quick Scan",
        "description": "Fast SYN scan with service version detection on common ports",
        "category": "recon",
        "binary": "nmap",
        "default_flags": "-sV -sC --open",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.1", "required": True, "description": "Target IP or hostname"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external", "internal", "web"],
        "is_builtin": True,
    },
    {
        "name": "Nmap - Full Port Scan",
        "description": "Full TCP port scan across all 65535 ports",
        "category": "recon",
        "binary": "nmap",
        "default_flags": "-sV -sC -p-",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.1", "required": True, "description": "Target IP or hostname"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external", "internal"],
        "is_builtin": True,
    },
    {
        "name": "Nmap - UDP Scan",
        "description": "UDP scan on common ports",
        "category": "recon",
        "binary": "nmap",
        "default_flags": "-sU --top-ports 200",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.1", "required": True, "description": "Target IP or hostname"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "nmap - Host Discovery",
        "description": "Ping sweep to identify live hosts across a subnet — fast Phase 1 host discovery without port scanning or IDS-triggering service probes.",
        "category": "recon",
        "binary": "nmap-sweep",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.0/24", "required": True, "description": "CIDR range or IP to sweep"},
        ],
        "agent_mode": "passive",
        "scope_types": ["ip"],
        "workflow_tags": ["internal", "external"],
        "is_builtin": True,
    },
    {
        "name": "Masscan - Fast Port Scan",
        "description": "Extremely fast TCP port scanner — useful for large IP ranges where nmap would be too slow. Added via user-tools.txt as a Pattern A custom tool example.",
        "category": "recon",
        "binary": "masscan",
        "default_flags": "--rate=1000",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.0/24", "required": True, "description": "Target IP or CIDR range"},
            {"name": "ports", "flag": "-p", "placeholder": "1-65535", "required": True, "description": "Port range to scan"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["external", "internal"],
        "is_builtin": False,
    },
    {
        "name": "whois",
        "description": "Domain registration and ownership lookup",
        "category": "recon",
        "binary": "whois",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "target.com", "required": True, "description": "Domain or IP"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external"],
        "is_builtin": True,
    },
    {
        "name": "dig",
        "description": "DNS lookup and zone transfer attempt",
        "category": "recon",
        "binary": "dig",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "target.com", "required": True, "description": "Domain"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external", "web", "internal"],
        "is_builtin": True,
    },
    {
        "name": "dnsrecon",
        "description": "DNS enumeration: zone transfers, standard records, brute force, and reverse lookups",
        "category": "recon",
        "binary": "dnsrecon",
        "default_flags": "-t std",
        "parameters": [
            {"name": "domain", "flag": "-d", "placeholder": "target.com", "required": True, "description": "Target domain"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external", "web", "internal"],
        "is_builtin": True,
    },
    {
        "name": "nslookup",
        "description": "Quick DNS record lookup — A, MX, NS, TXT, CNAME, or reverse-lookup an IP against any resolver",
        "category": "recon",
        "binary": "nslookup",
        "default_flags": "",
        "parameters": [
            {"name": "type",   "flag": "-type",   "placeholder": "MX, NS, TXT, CNAME, ANY", "required": False, "description": "Record type (default: A)"},
            {"name": "target", "flag": "",         "placeholder": "target.com or 192.168.1.1", "required": True,  "description": "Domain or IP to look up"},
            {"name": "server", "flag": "",         "placeholder": "8.8.8.8",                  "required": False, "description": "DNS server to query (default: system resolver)"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external", "internal", "web"],
        "is_builtin": True,
    },
    {
        "name": "BBOT - Subdomain Enum",
        "description": "Recursive attack surface mapping — subdomains, emails, web tech discovery, and more",
        "category": "recon",
        "binary": "bbot",
        "default_flags": "-p subdomain-enum",
        "parameters": [
            {"name": "target", "flag": "-t", "placeholder": "target.com", "required": True, "description": "Target domain"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external"],
        "is_builtin": True,
    },
    {
        "name": "subfinder",
        "description": "Fast passive subdomain enumeration using 40+ OSINT sources — lightweight first pass before active DNS brute-forcing",
        "category": "recon",
        "binary": "subfinder",
        "default_flags": "-silent",
        "parameters": [
            {"name": "domain", "flag": "-d", "placeholder": "target.com", "required": True, "description": "Target domain"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external", "web"],
        "is_builtin": True,
    },
    {
        "name": "Subdominator",
        "description": "Passive subdomain enumeration using 73+ OSINT sources (requires Python 3.13+; add to user-pip.txt to install)",
        "category": "recon",
        "binary": "subdominator",
        "default_flags": "",
        "parameters": [
            {"name": "domain", "flag": "-d", "placeholder": "target.com", "required": True, "description": "Target domain"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external"],
        "is_builtin": False,
    },
    # ── WEB ───────────────────────────────────────────────────────────────────
    {
        "name": "Gobuster - Dir Enum",
        "description": "Directory and file enumeration against a web target",
        "category": "web",
        "binary": "gobuster",
        "default_flags": "dir -t 50 -x php,html,txt",
        "parameters": [
            {"name": "url", "flag": "-u", "placeholder": "http://10.10.10.1", "required": True, "description": "Target URL"},
            {"name": "wordlist", "flag": "-w", "placeholder": "/wordlists/Discovery/Web-Content/common.txt", "required": True, "description": "Wordlist path"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["web"],
        "is_builtin": True,
    },
    {
        "name": "Gobuster - Vhost Enum",
        "description": "Virtual host enumeration",
        "category": "web",
        "binary": "gobuster",
        "default_flags": "vhost --append-domain",
        "parameters": [
            {"name": "url", "flag": "-u", "placeholder": "http://10.10.10.1", "required": True, "description": "Base URL"},
            {"name": "domain", "flag": "-d", "placeholder": "target.htb", "required": True, "description": "Base domain"},
            {"name": "wordlist", "flag": "-w", "placeholder": "/wordlists/Discovery/DNS/subdomains-top1million-5000.txt", "required": True, "description": "Wordlist path"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["web"],
        "is_builtin": True,
    },
    {
        "name": "ffuf - Directory Fuzz",
        "description": "Fast web fuzzer for directories and files",
        "category": "web",
        "binary": "ffuf",
        "default_flags": "-c -mc 200,301,302,403",
        "parameters": [
            {"name": "url", "flag": "-u", "placeholder": "http://10.10.10.1/FUZZ", "required": True, "description": "URL with FUZZ keyword"},
            {"name": "wordlist", "flag": "-w", "placeholder": "/wordlists/Discovery/Web-Content/common.txt", "required": True, "description": "Wordlist path"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["web"],
        "is_builtin": True,
    },
    {
        "name": "feroxbuster",
        "description": "Fast recursive content discovery with auto-tuning and smart filtering",
        "category": "web",
        "binary": "feroxbuster",
        "default_flags": "--auto-tune",
        "parameters": [
            {"name": "url", "flag": "-u", "placeholder": "http://10.10.10.1", "required": True, "description": "Target URL"},
            {"name": "wordlist", "flag": "-w", "placeholder": "/wordlists/Discovery/Web-Content/common.txt", "required": True, "description": "Wordlist path"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["web"],
        "is_builtin": True,
    },
    {
        "name": "Nikto",
        "description": "Web server vulnerability scanner",
        "category": "web",
        "binary": "nikto",
        "default_flags": "-C all",
        "parameters": [
            {"name": "host", "flag": "-h", "placeholder": "10.10.10.1", "required": True, "description": "Target host"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["web"],
        "is_builtin": True,
    },
    {
        "name": "WhatWeb",
        "description": "Web technology fingerprinting",
        "category": "web",
        "binary": "whatweb",
        "default_flags": "-a 3",
        "parameters": [
            {"name": "target", "placeholder": "http://10.10.10.1", "required": True, "description": "Target URL"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["web"],
        "is_builtin": True,
    },
    {
        "name": "WPScan",
        "description": "WordPress vulnerability scanner — enumerates users, vulnerable plugins, and themes",
        "category": "web",
        "binary": "wpscan",
        "default_flags": "--enumerate u,vp",
        "parameters": [
            {"name": "url", "flag": "--url", "placeholder": "http://10.10.10.1", "required": True, "description": "WordPress URL"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["web"],
        "is_builtin": True,
    },
    {
        "name": "sslscan",
        "description": "SSL/TLS version and cipher suite enumeration",
        "category": "web",
        "binary": "sslscan",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "target.com:443", "required": True, "description": "Target host:port"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["web", "external"],
        "is_builtin": True,
    },
    {
        "name": "wafw00f",
        "description": "Web Application Firewall detection and fingerprinting",
        "category": "web",
        "binary": "wafw00f",
        "default_flags": "-a",
        "parameters": [
            {"name": "url", "placeholder": "http://target.com", "required": True, "description": "Target URL"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["web", "external"],
        "is_builtin": True,
    },
    # ── ENUM ──────────────────────────────────────────────────────────────────
    {
        "name": "enum4linux-ng",
        "description": "SMB/Windows enumeration",
        "category": "enum",
        "binary": "enum4linux-ng",
        "default_flags": "-A",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.1", "required": True, "description": "Target IP"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "smbclient - List Shares",
        "description": "List SMB shares on a target",
        "category": "enum",
        "binary": "smbclient",
        "default_flags": "-N",
        "parameters": [
            {"name": "target", "flag": "-L", "placeholder": "10.10.10.1", "required": True, "description": "Target IP"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "SNMPwalk",
        "description": "SNMP enumeration",
        "category": "enum",
        "binary": "snmpwalk",
        "default_flags": "-v2c -c public",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.1", "required": True, "description": "Target IP"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "netexec - SMB",
        "description": "SMB host discovery, share enumeration, and credential validation. Common extra_flags: --shares (list shares), --sam (dump SAM), --lsa (dump LSA), --ntds (DCSync all hashes), --rid-brute (enumerate users), --sessions (list active sessions), --loggedon-users. Auth: -u USER -p PASS or -u USER -H NTHASH for pass-the-hash.",
        "category": "enum",
        "binary": "nxc-smb",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.0/24", "required": True, "description": "Target IP or CIDR range"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "netexec - LDAP",
        "description": "LDAP enumeration of Active Directory. Common extra_flags: --users (dump all users), --groups (dump groups), --pass-pol (password policy), --asreproast FILE (AS-REP roast), --kerberoasting FILE (kerberoast), --gmsa (dump GMSA passwords), --bloodhound (collect BH data). Auth: -u USER -p PASS or -H NTHASH.",
        "category": "enum",
        "binary": "nxc-ldap",
        "default_flags": "--users --groups --pass-pol",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.1", "required": True, "description": "Domain controller IP"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "kerbrute - User Enum",
        "description": "Kerberos username enumeration against a domain controller (no lockout risk)",
        "category": "enum",
        "binary": "kerbrute",
        "default_flags": "userenum",
        "parameters": [
            {"name": "domain", "flag": "-d", "placeholder": "domain.local", "required": True, "description": "Target domain"},
            {"name": "dc", "flag": "--dc", "placeholder": "10.10.10.1", "required": True, "description": "Domain controller IP"},
            {"name": "wordlist", "placeholder": "/wordlists/Usernames/top-usernames-shortlist.txt", "required": True, "description": "Username wordlist"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-secretsdump",
        "description": "Dump SAM, LSA, and NTDS secrets remotely using valid credentials",
        "category": "enum",
        "binary": "impacket-secretsdump",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "DOMAIN/user:password@10.10.10.1", "required": True, "description": "Auth string: DOMAIN/user:pass@host"},
        ],
        "agent_mode": "exploit",
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-GetNPUsers",
        "description": "AS-REP roasting — find accounts with Kerberos pre-authentication disabled and request hashes",
        "category": "enum",
        "binary": "impacket-GetNPUsers",
        "default_flags": "-no-pass -request",
        "parameters": [
            {"name": "dc", "flag": "-dc-ip", "placeholder": "10.10.10.1", "required": True, "description": "Domain controller IP"},
            {"name": "domain", "placeholder": "domain.local/", "required": True, "description": "Target domain with trailing slash"},
            {"name": "outputfile", "flag": "-outputfile", "placeholder": "/data/<session_id>/asrep_hashes.txt", "required": False, "description": "Save hashes to file for john (use session output dir path from prompt)"},
        ],
        "agent_mode": "exploit",
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-GetUserSPNs",
        "description": "Kerberoasting — request TGS tickets for all SPN accounts for offline hash cracking",
        "category": "enum",
        "binary": "impacket-GetUserSPNs",
        "default_flags": "-request",
        "parameters": [
            {"name": "dc", "flag": "-dc-ip", "placeholder": "10.10.10.1", "required": True, "description": "Domain controller IP"},
            {"name": "target", "placeholder": "domain.local/user:password", "required": True, "description": "Auth string: domain.local/user:pass"},
            {"name": "outputfile", "flag": "-outputfile", "placeholder": "/data/<session_id>/kerb_hashes.txt", "required": False, "description": "Save hashes to file for john (use session output dir path from prompt)"},
        ],
        "agent_mode": "exploit",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "ldapdomaindump",
        "description": "Dump all Active Directory objects (users, groups, OUs, GPOs, computers) via LDAP into structured JSON and HTML files",
        "category": "enum",
        "binary": "ldapdomaindump",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.1", "required": True, "description": "Domain controller IP"},
            {"name": "username", "flag": "-u", "placeholder": "DOMAIN\\user", "required": False, "description": "Username for auth (omit for null session attempt)"},
            {"name": "password", "flag": "-p", "placeholder": "password", "required": False, "description": "Password"},
            {"name": "outputdir", "flag": "-o", "placeholder": "/data/<session_id>/ldap", "required": False, "description": "Output directory for JSON/HTML dump files"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "rpcclient",
        "description": "RPC enumeration — null session checks, user/group/share listing, and domain info via MS-RPCE",
        "category": "enum",
        "binary": "rpcclient",
        "default_flags": "-U \"\" -N",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.1", "required": True, "description": "Domain controller IP"},
            {"name": "command", "flag": "-c", "placeholder": "enumdomusers", "required": False, "description": "RPC command (e.g. enumdomusers, enumdomgroups, querydominfo)"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "evil-winrm",
        "description": "WinRM shell — run PowerShell commands remotely using a password or NTLM hash (pass-the-hash)",
        "category": "enum",
        "binary": "evil-winrm",
        "default_flags": "",
        "parameters": [
            {"name": "target", "flag": "-i", "placeholder": "10.10.10.1", "required": True, "description": "Target IP"},
            {"name": "username", "flag": "-u", "placeholder": "administrator", "required": True, "description": "Username"},
            {"name": "password", "flag": "-p", "placeholder": "password", "required": False, "description": "Password (use hash for pass-the-hash instead)"},
            {"name": "hash", "flag": "-H", "placeholder": "aad3b435b51404eeaad3b435b51404ee:...", "required": False, "description": "NTLM hash for pass-the-hash"},
            {"name": "command", "flag": "-c", "placeholder": "whoami", "required": False, "description": "PowerShell command to execute non-interactively"},
        ],
        "agent_mode": "exploit",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "bloodhound-python",
        "description": "Active Directory data collector — dumps AD objects and attack paths as JSON. Import the output ZIP into BloodHound CE for graph analysis.",
        "category": "enum",
        "binary": "bloodhound-python",
        "default_flags": "-c All --zip",
        "parameters": [
            {"name": "domain", "flag": "-d", "placeholder": "domain.local", "required": True, "description": "Target domain"},
            {"name": "dc", "flag": "--ns", "placeholder": "10.10.10.1", "required": True, "description": "Domain controller / nameserver IP"},
            {"name": "username", "flag": "-u", "placeholder": "user", "required": True, "description": "Domain username"},
            {"name": "password", "flag": "-p", "placeholder": "password", "required": True, "description": "Password"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "netexec - RDP",
        "description": "Check RDP availability and test credentials across Windows hosts in a subnet. Add -u/-p or -H for pass-the-hash.",
        "category": "enum",
        "binary": "nxc-rdp",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.0/24", "required": True, "description": "Target IP or CIDR range"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "netexec - MSSQL",
        "description": "Enumerate MSSQL instances and test authentication across a subnet. Use -x to execute commands if xp_cmdshell is enabled.",
        "category": "enum",
        "binary": "nxc-mssql",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.0/24", "required": True, "description": "Target IP or CIDR range"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "netexec - WinRM",
        "description": "Check WinRM availability and test credentials against Windows hosts. Add -u/-p or -H for pass-the-hash.",
        "category": "enum",
        "binary": "nxc-winrm",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "10.10.10.0/24", "required": True, "description": "Target IP or CIDR range"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "smbmap",
        "description": "Enumerate SMB share permissions — find readable and writable shares using null sessions or valid credentials",
        "category": "enum",
        "binary": "smbmap",
        "default_flags": "",
        "parameters": [
            {"name": "host", "flag": "-H", "placeholder": "10.10.10.1", "required": True, "description": "Target host IP"},
            {"name": "username", "flag": "-u", "placeholder": "user", "required": False, "description": "Username (omit for null session)"},
            {"name": "password", "flag": "-p", "placeholder": "password", "required": False, "description": "Password"},
            {"name": "domain", "flag": "-d", "placeholder": "DOMAIN", "required": False, "description": "Domain name"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "Responder",
        "description": "LLMNR/NBT-NS/MDNS poisoner — captures NTLMv2 hashes from broadcast traffic. MANUAL USE ONLY: must be run from a host on the target subnet. The AI references this tool in reasoning but will never run it autonomously.",
        "category": "enum",
        "binary": "responder",
        "default_flags": "-wF",
        "parameters": [
            {"name": "interface", "flag": "-I", "placeholder": "eth0", "required": True, "description": "Network interface to listen on"},
        ],
        "agent_mode": "never",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-wmiexec",
        "description": "WMI-based remote command execution — runs commands via DCOM/WMI without touching disk. Useful when WinRM is closed (no port 5985) but WMI is open (port 135).",
        "category": "enum",
        "binary": "impacket-wmiexec",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "DOMAIN/user:password@10.10.10.1", "required": True, "description": "Auth string: DOMAIN/user:pass@host (or use -hashes for pass-the-hash)"},
            {"name": "command", "flag": "-c", "placeholder": "whoami", "required": False, "description": "Command to execute (leave empty for interactive shell)"},
        ],
        "agent_mode": "exploit",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-psexec",
        "description": "PSExec-style remote execution — uploads a service binary to ADMIN$ and runs commands as SYSTEM. Requires admin credentials and SMB write access to ADMIN$.",
        "category": "enum",
        "binary": "impacket-psexec",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "DOMAIN/user:password@10.10.10.1", "required": True, "description": "Auth string: DOMAIN/user:pass@host (or use -hashes for pass-the-hash)"},
            {"name": "command", "flag": "-c", "placeholder": "whoami", "required": False, "description": "Command to execute (leave empty for interactive shell)"},
        ],
        "agent_mode": "exploit",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-lookupsid",
        "description": "SID brute-force enumeration — discovers domain user and group accounts by iterating RIDs via null or authenticated session. Useful for username discovery without a wordlist.",
        "category": "enum",
        "binary": "impacket-lookupsid",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "DOMAIN/user:password@10.10.10.1", "required": True, "description": "Auth string (use DOMAIN/guest:@IP for unauthenticated)"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-findDelegation",
        "description": "Enumerate Kerberos delegation — finds computers and accounts configured with unconstrained, constrained, or resource-based constrained delegation. Key input for privilege escalation planning.",
        "category": "enum",
        "binary": "impacket-findDelegation",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "DOMAIN/user:password", "required": True, "description": "Auth string: DOMAIN/user:pass"},
            {"name": "dc", "flag": "-dc-ip", "placeholder": "10.10.10.1", "required": True, "description": "Domain controller IP"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-getST",
        "description": "Request a Kerberos service ticket via S4U2Self/S4U2Proxy — enables impersonation under constrained delegation and silver ticket attacks. Use after findDelegation identifies a delegation-enabled account. Requires -spn <SPN> in extra_flags (e.g. -spn cifs/TARGET.domain.local) plus optionally -impersonate <user>.",
        "category": "enum",
        "binary": "impacket-getST",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "DOMAIN/user:password", "required": True, "description": "Auth string: DOMAIN/user:pass (or -hashes :NTHASH for pass-the-hash)"},
            {"name": "dc", "flag": "-dc-ip", "placeholder": "10.10.10.1", "required": True, "description": "Domain controller IP"},
        ],
        "agent_mode": "exploit",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-addcomputer",
        "description": "Add a computer account to the domain — prerequisite for Resource-Based Constrained Delegation (RBCD) attacks when a user has CreateChild rights on an OU. The new computer account is then used with getST for impersonation.",
        "category": "enum",
        "binary": "impacket-addcomputer",
        "default_flags": "-method LDAPS",
        "parameters": [
            {"name": "target", "placeholder": "DOMAIN/user:password", "required": True, "description": "Auth string: DOMAIN/user:pass"},
            {"name": "dc", "flag": "-dc-ip", "placeholder": "10.10.10.1", "required": True, "description": "Domain controller IP"},
        ],
        "agent_mode": "exploit",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-smbexec",
        "description": "SMB-based remote execution via a temporary service — alternative to psexec that avoids writing a binary to disk. Useful when psexec is blocked by AV/EDR.",
        "category": "enum",
        "binary": "impacket-smbexec",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "DOMAIN/user:password@10.10.10.1", "required": True, "description": "Auth string: DOMAIN/user:pass@host (or use -hashes :<NT> for pass-the-hash)"},
        ],
        "agent_mode": "exploit",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-Get-GPPPassword",
        "description": "Find plaintext credentials stored in Group Policy Preferences (GPP) XML files in SYSVOL — a very common AD misconfiguration. Works via null session or with credentials.",
        "category": "enum",
        "binary": "impacket-Get-GPPPassword",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "DOMAIN/user:password@10.10.10.1", "required": True, "description": "Auth string: DOMAIN/user:pass@DC (null session: DOMAIN/guest:@DC)"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-GetLAPSPassword",
        "description": "Retrieve LAPS-managed local administrator passwords from Active Directory. Requires read permission on the ms-Mcs-AdmPwd attribute for the target computer object.",
        "category": "enum",
        "binary": "impacket-GetLAPSPassword",
        "default_flags": "",
        "parameters": [
            {"name": "target", "placeholder": "DOMAIN/user:password@10.10.10.1", "required": True, "description": "Auth string: DOMAIN/user:pass@DC"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "certipy",
        "description": "ADCS attack framework — enumerate certificate templates for ESC1-8 vulnerabilities, request certificates exploiting misconfigured templates, and authenticate with the resulting cert to get a TGT or NT hash.",
        "category": "enum",
        "binary": "certipy-ad",
        "default_flags": "find -vulnerable -stdout",
        "parameters": [
            {"name": "user", "flag": "-u", "placeholder": "user@corp.local", "required": True, "description": "Username (UPN format: user@domain)"},
            {"name": "password", "flag": "-p", "placeholder": "password", "required": False, "description": "Password"},
            {"name": "dc", "flag": "-dc-ip", "placeholder": "10.10.10.1", "required": True, "description": "Domain controller IP"},
        ],
        "agent_mode": "exploit",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "hashcat",
        "description": "CPU-based hash cracking with rule support — complements john for NTLM, Kerberos TGS/AS-REP, and MD5 cracking. Especially useful with rule files for password mutation.",
        "category": "util",
        "binary": "hashcat",
        "default_flags": "--force",
        "parameters": [
            {"name": "hashfile", "placeholder": "/data/<session_id>/hashes.txt", "required": True, "description": "File containing hashes — use session output dir path"},
            {"name": "wordlist", "placeholder": "/wordlists/Passwords/Leaked-Databases/rockyou.txt", "required": False, "description": "Wordlist path"},
            {"name": "mode", "flag": "-m", "placeholder": "1000", "required": True, "description": "Hash mode: 1000=NTLM, 13100=Kerberoast (TGS), 18200=AS-REP roast"},
        ],
        "agent_mode": "active",
        "scope_types": [],
        "workflow_tags": ["internal", "external", "web"],
        "is_builtin": True,
    },
    {
        "name": "ldapsearch",
        "description": "Raw LDAP queries against Active Directory — enumerate users, groups, OUs, GPOs, password policies, and ADCS templates. More flexible than ldapdomaindump for targeted queries.",
        "category": "enum",
        "binary": "ldapsearch",
        "default_flags": "-x -LLL",
        "parameters": [
            {"name": "host", "flag": "-H", "placeholder": "ldap://10.10.10.1", "required": True, "description": "LDAP URI: ldap://IP or ldaps://IP"},
            {"name": "binddn", "flag": "-D", "placeholder": "DOMAIN\\user", "required": False, "description": "Bind DN (username) — omit for anonymous bind"},
            {"name": "password", "flag": "-w", "placeholder": "password", "required": False, "description": "Password"},
            {"name": "base", "flag": "-b", "placeholder": "DC=corp,DC=local", "required": True, "description": "Search base DN"},
            {"name": "filter", "placeholder": "(objectClass=user)", "required": False, "description": "LDAP filter"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    {
        "name": "impacket-ntlmrelayx",
        "description": "NTLM relay attack — relays NTLMv2 hashes captured by Responder to a target service (SMB, LDAP, HTTP). MANUAL USE ONLY: requires Responder running simultaneously on the same subnet. AI references this alongside Responder but will never run it autonomously.",
        "category": "enum",
        "binary": "impacket-ntlmrelayx",
        "default_flags": "-smb2support",
        "parameters": [
            {"name": "target", "flag": "-t", "placeholder": "smb://10.10.10.1", "required": True, "description": "Relay target: smb://IP, ldap://IP, or http://IP"},
            {"name": "command", "flag": "-c", "placeholder": "whoami", "required": False, "description": "Command to execute on the target if relay succeeds"},
        ],
        "agent_mode": "never",
        "scope_types": ["ip"],
        "workflow_tags": ["internal"],
        "is_builtin": True,
    },
    # ── VULN ──────────────────────────────────────────────────────────────────
    {
        "name": "Nuclei",
        "description": "Template-based vulnerability scanner",
        "category": "vuln",
        "binary": "nuclei",
        "default_flags": "-severity medium,high,critical",
        "parameters": [
            {"name": "target", "flag": "-u", "placeholder": "http://10.10.10.1", "required": True, "description": "Target URL"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["web", "external"],
        "is_builtin": True,
    },
    {
        "name": "Nuclei - Network Scan",
        "description": "Network protocol CVE templates — scans Windows hosts for known vulnerabilities: MS17-010 (EternalBlue), BlueKeep, PrintNightmare, SMB/RDP/MSSQL CVEs.",
        "category": "vuln",
        "binary": "nuclei-network",
        "default_flags": "-severity medium,high,critical",
        "parameters": [
            {"name": "target", "flag": "-u", "placeholder": "10.10.10.1", "required": True, "description": "Target IP or hostname"},
        ],
        "agent_mode": "active",
        "scope_types": ["ip"],
        "workflow_tags": ["internal", "external"],
        "is_builtin": True,
    },
    {
        "name": "SQLMap",
        "description": "Automated SQL injection detection and exploitation",
        "category": "vuln",
        "binary": "sqlmap",
        "default_flags": "--batch --level=2 --risk=1",
        "parameters": [
            {"name": "url", "flag": "-u", "placeholder": "http://10.10.10.1/page?id=1", "required": True, "description": "Target URL with parameter"},
        ],
        "agent_mode": "exploit",
        "workflow_tags": ["web"],
        "is_builtin": True,
    },
    # ── CLOUD ─────────────────────────────────────────────────────────────────
    {
        "name": "cloud_enum",
        "description": "Enumerate publicly exposed AWS S3, Azure Blob, and GCP Storage resources for a target",
        "category": "cloud",
        "binary": "cloud_enum",
        "default_flags": "",
        "parameters": [
            {"name": "keyword", "flag": "-k", "placeholder": "targetcorp", "required": True, "description": "Company name or keyword to enumerate"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external"],
        "is_builtin": True,
    },
    # ── SECRETS ───────────────────────────────────────────────────────────────
    {
        "name": "trufflehog",
        "description": "Scan git repos for leaked secrets and credentials, with live API validation",
        "category": "secrets",
        "binary": "trufflehog-git",
        "default_flags": "--only-verified",
        "parameters": [
            {"name": "repo", "placeholder": "https://github.com/org/repo", "required": True, "description": "Git repository URL"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external"],
        "is_builtin": True,
    },
    # ── HTTP PROBES ───────────────────────────────────────────────────────────
    # These thin wrappers around curl each get their own binary name so the agent
    # can pick the right one without needing extra_flags for every variant.
    {
        "name": "curl-probe",
        "description": "HTTP GET — returns status line, response headers, and body. Good first probe of any endpoint to see what it returns.",
        "category": "web",
        "binary": "curl-probe",
        "default_flags": "",
        "parameters": [
            {"name": "url", "placeholder": "http://target.com/api/endpoint", "required": True, "description": "Full URL to probe"},
        ],
        "agent_mode": "passive",
        "scope_types": ["web"],
        "workflow_tags": ["web", "external"],
        "is_builtin": True,
    },
    {
        "name": "curl-headers",
        "description": "Fetch HTTP response headers only (HEAD request). Use to check security headers: HSTS, CSP, X-Frame-Options, X-Content-Type-Options, CORS, cookies.",
        "category": "web",
        "binary": "curl-headers",
        "default_flags": "",
        "parameters": [
            {"name": "url", "placeholder": "http://target.com", "required": True, "description": "Target URL"},
        ],
        "agent_mode": "passive",
        "scope_types": ["web"],
        "workflow_tags": ["web", "external"],
        "is_builtin": True,
    },
    {
        "name": "curl-cors",
        "description": "Test CORS policy — sends a preflight OPTIONS request with Origin: evil.com. Look for Access-Control-Allow-Origin: * or reflection of the attacker origin.",
        "category": "web",
        "binary": "curl-cors",
        "default_flags": "",
        "parameters": [
            {"name": "url", "placeholder": "http://target.com/api/endpoint", "required": True, "description": "Endpoint to test"},
        ],
        "agent_mode": "passive",
        "scope_types": ["web"],
        "workflow_tags": ["web", "external"],
        "is_builtin": True,
    },
    {
        "name": "curl-json",
        "description": "HTTP GET with Accept: application/json — probes API endpoints and returns the JSON response. Good for unauthenticated API enumeration.",
        "category": "web",
        "binary": "curl-json",
        "default_flags": "",
        "parameters": [
            {"name": "url", "placeholder": "http://target.com/api/v1/users", "required": True, "description": "API endpoint URL"},
        ],
        "agent_mode": "passive",
        "scope_types": ["web"],
        "workflow_tags": ["web", "external"],
        "is_builtin": True,
    },
    {
        "name": "curl-redirect",
        "description": "HTTP GET following all redirects (-L), showing the final destination and each hop. Useful to map redirect chains or detect open redirects.",
        "category": "web",
        "binary": "curl-redirect",
        "default_flags": "",
        "parameters": [
            {"name": "url", "placeholder": "http://target.com/redirect?url=http://evil.com", "required": True, "description": "URL to follow"},
        ],
        "agent_mode": "passive",
        "scope_types": ["web"],
        "workflow_tags": ["web", "external"],
        "is_builtin": True,
    },
    {
        "name": "nc-banner",
        "description": "TCP banner grab — connects to host:port and captures the service banner. Useful for identifying services on non-standard ports.",
        "category": "recon",
        "binary": "nc-banner",
        "default_flags": "",
        "parameters": [
            {"name": "host", "placeholder": "10.10.10.1", "required": True, "description": "Target host or IP"},
            {"name": "port", "placeholder": "8080", "required": True, "description": "TCP port"},
        ],
        "agent_mode": "passive",
        "scope_types": [],
        "workflow_tags": ["external", "internal", "web"],
        "is_builtin": True,
    },
    # ── BASH ──────────────────────────────────────────────────────────────────
    {
        "name": "bash - Free-form Command",
        "description": "Run any arbitrary shell command when no specific tool fits. Put the COMPLETE command in extra_flags (e.g. \"curl -s 'http://target/api/users' | jq .\"). Requires human approval before execution.",
        "category": "util",
        "binary": "bash",
        "default_flags": "",
        "parameters": [],
        "agent_mode": "exploit",
        "scope_types": [],
        "workflow_tags": ["web", "external", "internal"],
        "is_builtin": True,
    },
    # ── UTIL ──────────────────────────────────────────────────────────────────
    {
        "name": "john",
        "description": "Offline password cracking — crack NTLM hashes, Kerberos TGS/AS-REP tickets, and other hash formats against a wordlist",
        "category": "util",
        "binary": "john",
        "default_flags": "",
        "parameters": [
            {"name": "hashfile", "placeholder": "/data/<session_id>/hashes.txt", "required": True, "description": "File containing hashes to crack — use the session output dir path"},
            {"name": "wordlist", "flag": "--wordlist", "placeholder": "/wordlists/Passwords/Leaked-Databases/rockyou.txt", "required": False, "description": "Wordlist path"},
            {"name": "format", "flag": "--format", "placeholder": "nt", "required": False, "description": "Hash format: nt, krb5tgs, krb5asrep, sha512crypt"},
        ],
        "agent_mode": "active",
        "scope_types": [],
        "workflow_tags": ["internal", "external", "web"],
        "is_builtin": True,
    },
    {
        "name": "Hydra - SSH",
        "description": "SSH credential brute force",
        "category": "util",
        "binary": "hydra",
        "default_flags": "-t 4",
        "parameters": [
            {"name": "userlist", "flag": "-L", "placeholder": "/wordlists/Usernames/top-usernames-shortlist.txt", "required": True, "description": "Username list"},
            {"name": "passlist", "flag": "-P", "placeholder": "/wordlists/Passwords/Common-Credentials/10-million-password-list-top-1000.txt", "required": True, "description": "Password list"},
            {"name": "target", "placeholder": "10.10.10.1", "required": True, "description": "Target IP"},
            {"name": "protocol", "placeholder": "ssh", "required": True, "description": "Service (ssh, ftp, rdp, etc.)"},
        ],
        "agent_mode": "exploit",
        "workflow_tags": ["internal", "external"],
        "is_builtin": True,
    },
    {
        "name": "searchsploit",
        "description": "Search the local Exploit-DB for known exploits matching a service, version, or CVE",
        "category": "util",
        "binary": "searchsploit",
        "default_flags": "--color",
        "parameters": [
            {"name": "query", "placeholder": "apache 2.4", "required": True, "description": "Search term (service, version, or CVE)"},
        ],
        "agent_mode": "passive",
        "workflow_tags": ["external", "internal", "web"],
        "is_builtin": True,
    },
    {
        "name": "CeWL",
        "description": "Crawl a website and generate a custom wordlist from its content",
        "category": "util",
        "binary": "cewl",
        "default_flags": "-d 2 -m 5",
        "parameters": [
            {"name": "url", "placeholder": "http://target.com", "required": True, "description": "Target URL to crawl"},
        ],
        "agent_mode": "active",
        "workflow_tags": ["web", "external"],
        "is_builtin": True,
    },
]


async def seed_default_tools():
    async with AsyncSessionLocal() as db:
        for tool_data in DEFAULT_TOOLS:
            result = await db.execute(select(Tool).where(Tool.name == tool_data["name"]))
            existing = result.scalar_one_or_none()
            if not existing:
                tool = Tool(**tool_data)
                db.add(tool)
            else:
                # Keep builtin tool definitions in sync with seed data
                existing.category = tool_data["category"]
                existing.binary = tool_data["binary"]
                existing.default_flags = tool_data["default_flags"]
                existing.parameters = tool_data["parameters"]
                existing.description = tool_data["description"]
                existing.workflow_tags = tool_data.get("workflow_tags", [])
                existing.agent_mode = tool_data.get("agent_mode", existing.agent_mode or "auto")
                existing.scope_types = tool_data.get("scope_types", existing.scope_types or [])
                existing.is_builtin = tool_data.get("is_builtin", existing.is_builtin)
        await db.commit()
